### ISSUE TITLE
GoogleMaps error

### ISSUE THREAD

**Issue by Lagaffe** [emberjs/super-rentals#28]
creating the maps on the listing throws a GoogleMaps error:
InvalidValueError: setTitle: not a string

The issue is that in /app/utils/google-maps.js, on line 20, the argument 'location' of the 'pinLocation' function is overwritten. While on line 23 the original value is expected.

This should also be corrected in the tutorial.

**Comment by locks** [comment]
Can you send the relevant PRs please? Thank you!

**Comment by Lagaffe** [comment]
I've submitted a PR. Once you accept it, I'll create one for the guides repository.

**Comment by toddjordan** [comment]
Merged PR.  Looks like someone beat you to the fix in guides in https://github.com/emberjs/guides/pull/1549

**Comment by Lagaffe** [comment]
@toddjordan good to see it's been fixed in the guides, but now the variable naming isn't the same in the guides as in the reference app. Should this be fixed?

**Comment by toddjordan** [comment]
Ah, sure.  submit a PR aligning the new variable name with your
super-rental PR and I'll merge.  Thanks!
